### ISSUE TITLE
Download button won't work for SumoTorrents

### ISSUE THREAD

**Issue by BloodyRain2k** [ngosang/qBittorrent-plugins#1]
Seriously Github? Accidentally hitting enter submits instantly? Screw you...

Anyways, as I was trying to create this issue properly before my accidental enter screwed me over: the download button won't work for SumoTorrents.
From what I was able to gather so far does it come from the fact that not only are these dbags layering their download links double they don't even give you an actual torrent on top, you just get a location header sent back to you which contains the magnet link which qBit doesn't seem to understand, which is reasonable because that's retarded.

Copying the "guessed" download url of the torrent to the description page works though as that opens it then in the browser which is a bit more clever when it comes to such BS, but that's bothersome.

I'm not sure whenever or not there is something you can do about this to fix it, I've been trying a few things myself but this is only the 2nd plugin I'm even looking into so I have no idea what I'm doing, can't even get regex working : (

**Comment by ngosang** [comment]
Sumotorrent website changed recently and I can't get the proper download link. This search engine plugin is deprecated now.

**Comment by affaff** [comment]
It looks like the links can be found at: xpath: //div[@class='torrentInfo']//a

If the results of the anchor are not a valid torrent, can't we use the hash to find an alternative link?   xpath://table[@id='bits']//td[text()='Hash']/following-sibling::td

**Comment by BloodyRain2k** [comment]
The problem is that you get neither of these from the results page but already need to do a 2nd request.

On top of that did I already mention that their .torrent files are fake and are just a server response with a location header pointing to the magnet link.

So the only possible way I could think of without making it come to a crawl by firing a request for each result being added to the list is using "def download_torrent" or whatever it was which might be fired when you actually click the button.
I saw that one in a different plugin left over from debugging or something but I can't remember which now >.<
If that one is capable of telling qBit where to grab the torrent from it'd be possible to make it only fire the request for actually wanted torrents and with that go to the details page and grab the magnet link.


Edit: yeah my idea was working out, I managed to make it parse the magnet link instead now
https://dl.dropboxusercontent.com/u/59546146/sumotorrent.py

**Comment by affaff** [comment]
If you watch the HTTP traffic on a monitor like fiddler for windows, you can see that the "torrent" links are actually redirects to magnet links.   The specific magnet links they use use a base64 version of the hash, instead of the hex version.  To use this we would need to parse the magnet URL out of the response, then convert the btih property from base64 to hex string.  Once we have the hex string we can download the actual torrent from one of the free services around the web.

Python makes no sense to me. Things just plain don't execute and in this case, they don't throw any errors, I have no idea what it's doing.

I'm willing to learn and contribute, but, I'm totally baffled by it's choice as a language by anyone for any purpose.   It's not the 20th century any more.

I've been testing with the command line: 
>python nova2.py {engine} {category} {search_tokens}

it simple returns no results if the slightest error, with no indication of what the problem might be.

google is of no help on the issue because the examples that look totally straight forward, just plain don't work, and yes, no error message, no nothing.  Just empty results.

```
  descripURL = params['href'].strip()
  self.current_item['desc_link'] = descripURL;
  #self.current_item['link'] = 'http://localhost/torrentleach/leach.php?detailurl='+urllib.urlencode(descripURL);
  self.current_item['link'] = 'http://localhost/torrenthelper/sumotorrents.php?detailurl='+descripURL;                    
```
It should not be hard, it should be the super-simple type of operation that one does not even thing about.

So, as I've shown in the above python, I'm passing the torrent download URL to my php script on localhost the codes is exceptionally simple.

```
$detailHTML = file_get_contents($detailurl);
$hash = self::sumotorrentHash( $detailHTML,"//td[.='Hash']/following-sibling::td");
$torrentURL = "http://itorrents.org/torrent/$hash.torrent";
```

The proper place to put this logic is in the python:
`   def download_torrent(self, url):`

However since I can't even figure out how to urlencode a piece of text, generating anything of any really significance would be a ridiculous effort without even a basic starting framework.

My php localhost version is working fine, there is a cookie that needs to be set so that xxx can be downloaded without the prompt, I just haven't found it yet.   All the other torrents work fine.

I think using php in this way is the wrong answer, but, maybe it's the best wrong answer.   If a native python answer isn't developed, I'll probably put my php script out on the public  web someplace.

For someone that can make heads or tails out of that mess that is python, it should be very simple.

**Comment by ngosang** [comment]
@BloodyRain2k @affaff plugin updated. It's working again.
https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins
